fork = false
frame = "full"
idle = true
maximized = false
neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
# normal = [] # Will use the bundled Fira Code Nerd Font by default
size = 13.0

[[font.normal]]
family = "Liga SFMono Nerd Font"

[[font.normal]]
family = "FiraCode Nerd Font"

[[font.italic]]
family = "Operator Mono SSm Lig"
